name: Build
on:
  push:

permissions:
  contents: write
jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          distribution: "temurin"
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5
      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew build --stacktrace
          ls build/jar
      - name: Get plugin version
        if: github.ref == 'refs/heads/main'
        id: get_version
        run: |
          pluginVersion=$(grep '^pluginVersion=' gradle.properties)
          echo "$pluginVersion"
          echo "$pluginVersion" >> $GITHUB_OUTPUT
      - name: Check if tag exists locally
        if: github.ref == 'refs/heads/main'
        id: check_tag
        run: |
          tag="v${{ steps.get_version.outputs.pluginVersion }}"
          echo "Checking if tag '$tag' exists..."
          git fetch --tags
          if git rev-parse "$tag" >/dev/null 2>&1; then
            echo "Tag $tag exists."
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "Tag $tag does not exist."
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Upload to release
        if: steps.check_tag.outputs.exists == 'false' && github.ref == 'refs/heads/main'
        uses: svenstaro/upload-release-action@6b7fa9f267e90b50a19fef07b3596790bb941741 # v2
        continue-on-error: true
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: "v${{ steps.get_version.outputs.pluginVersion }}"
          file_glob: true
          file: build/jar/*.jar

      - name: Upload to Modrinth
        if: steps.check_tag.outputs.exists == 'false' && github.ref == 'refs/heads/main'
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
        run: |-
          ./gradlew modrinth
